### ISSUE TITLE
Where is BaseFragment

### ISSUE THREAD

**Issue by saikiran91** [michaldrabik/KotlinMVP#3]
How can I use fragments using this architecture?

**Comment by saikiran91** [comment]
How can you close without a answer?

**Comment by michaldrabik** [comment]
@saikiran91 Sorry, this issue skipped my attention and I've been doing some cleaning yesterday. It was over a year old so decided to close.

As for your question. There's no magic you simply swap Activity with a Fragment and hide it behind MvpView interface. You can use Activity to simply host a fragment and nothing else.
